const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function deploy(name, args = []) {
  const Factory = await ethers.getContractFactory(name);
  const contract = await Factory.deploy(...args);
  await contract.waitForDeployment();
  console.log(`${name} deployed at:`, await contract.getAddress());
  return contract;
}

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with:", deployer.address);

  const HLUSD = await deploy("HLUSD");
  const Card = await deploy("DeckWarsCard");
  const Deck = await deploy("DeckWarsDeck", [await Card.getAddress()]);
  const Rank = await deploy("DeckWarsRank");
  const Treasury = await deploy("DeckWarsTreasury", [
    deployer.address,
    await HLUSD.getAddress(),
  ]);
  const Quest = await deploy("DeckWarsQuest", [
    await Card.getAddress(),
    await HLUSD.getAddress(),
  ]);
  const SeasonPass = await deploy("DeckWarsSeasonPass", [
    await HLUSD.getAddress(),
    await Card.getAddress(),
    await Quest.getAddress(),
    await Treasury.getAddress(),
  ]);
  const Packs = await deploy("DeckWarsPacks", [
    await HLUSD.getAddress(),
    await Card.getAddress(),
    await Treasury.getAddress(),
  ]);
  const Battle = await deploy("DeckWarsBattle", [
    await Card.getAddress(),
    await Deck.getAddress(),
    await Rank.getAddress(),
    await Quest.getAddress(),
    await SeasonPass.getAddress(),
  ]);
  const Craft = await deploy("DeckWarsCraft", [
    await Card.getAddress(),
    await Quest.getAddress(),
  ]);
  const Season = await deploy("DeckWarsSeason");
  const Rewards = await deploy("DeckWarsRewards", [
    await Rank.getAddress(),
    await Card.getAddress(),
    await HLUSD.getAddress(),
  ]);

  const MINTER_ROLE = ethers.keccak256(ethers.toUtf8Bytes("MINTER_ROLE"));
  await (await Card.grantRole(MINTER_ROLE, await Craft.getAddress())).wait();
  await (await Card.grantRole(MINTER_ROLE, await Quest.getAddress())).wait();
  await (await Card.grantRole(MINTER_ROLE, await Packs.getAddress())).wait();
  await (await Card.grantRole(MINTER_ROLE, await Rewards.getAddress())).wait();
  await (await Card.grantRole(MINTER_ROLE, await SeasonPass.getAddress())).wait();

  await (await Deck.setBattleContract(await Battle.getAddress())).wait();
  await (await Rank.setBattleContract(await Battle.getAddress())).wait();
  await (await Quest.setBattleContract(await Battle.getAddress())).wait();
  await (await Quest.setCraftContract(await Craft.getAddress())).wait();
  await (await Quest.setSeasonPassContract(await SeasonPass.getAddress())).wait();
  await (await Treasury.addAuthorized(await Packs.getAddress())).wait();
  await (await Treasury.addAuthorized(await SeasonPass.getAddress())).wait();

  await (await Season.startSeason("Season 1: Dawn of DeckWars")).wait();
  await (await HLUSD.mint(deployer.address, ethers.parseEther("10000"))).wait();

  const addresses = {
    HLUSD: await HLUSD.getAddress(),
    DeckWarsCard: await Card.getAddress(),
    DeckWarsDeck: await Deck.getAddress(),
    DeckWarsBattle: await Battle.getAddress(),
    DeckWarsCraft: await Craft.getAddress(),
    DeckWarsQuest: await Quest.getAddress(),
    DeckWarsSeason: await Season.getAddress(),
    DeckWarsRank: await Rank.getAddress(),
    DeckWarsRewards: await Rewards.getAddress(),
    DeckWarsTreasury: await Treasury.getAddress(),
    DeckWarsSeasonPass: await SeasonPass.getAddress(),
    DeckWarsPacks: await Packs.getAddress(),
  };

  const network = await ethers.provider.getNetwork();
  const chainId = Number(network.chainId);
  const frontendDir = path.join(__dirname, "../frontend/src/contracts");
  fs.mkdirSync(path.join(frontendDir, "abis"), { recursive: true });
  fs.writeFileSync(
    path.join(frontendDir, "addresses.js"),
    `// Auto-generated by deploy.js — do not edit manually\nexport const CONTRACT_ADDRESSES = ${JSON.stringify(addresses, null, 2)};\nexport const CHAIN_ID = ${chainId};\n`
  );

  const contractNames = Object.keys(addresses).filter((k) => k !== "HLUSD");
  contractNames.push("HLUSD");
  for (const name of contractNames) {
    const artifact = require(path.join(
      __dirname,
      "../artifacts/contracts",
      `${name}.sol`,
      `${name}.json`
    ));
    fs.writeFileSync(
      path.join(frontendDir, `abis/${name}.json`),
      JSON.stringify(artifact.abi, null, 2)
    );
  }

  console.log("=== DEPLOYED ADDRESSES ===");
  console.log(JSON.stringify(addresses, null, 2));
  console.log("All addresses saved to frontend/src/contracts/addresses.js");
  console.log("All ABIs copied to frontend/src/contracts/abis/");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
